import '../globals.css'
import { cn } from '@/lib/utils'

import { ThemeProvider } from '@/components/ui/theme-provider'
import type { Metadata } from 'next'
import { Manrope as FontSans } from 'next/font/google'
import { Footer, Header } from '@/components/layout'
import { NextIntlClientProvider } from 'next-intl'
import { getMessages } from 'next-intl/server'

const fontSans = FontSans({
	subsets: ['latin', 'cyrillic'],
	variable: '--font-sans'
})

export const metadata: Metadata = {
	title: 'Create Next App',
	description: 'Generated by create next app'
}

export default async function RootLayout({
	children,
	params: { locale }
}: Readonly<{
	children: React.ReactNode
	params: { locale: string }
}>) {
	const messages = await getMessages()

	return (
		<html className='scroll-smooth scroll-mt-96' lang={locale}>
			<NextIntlClientProvider messages={messages}>
				<ThemeProvider>
					<body
						className={cn(
							'min-h-screen bg-background font-sans antialiased',
							fontSans.variable
						)}
					>
						<Header />
						<main>{children}</main>
						<Footer />
					</body>
				</ThemeProvider>
			</NextIntlClientProvider>
		</html>
	)
}
