import '../globals.css'
import { cn } from '@/lib/utils'

import type { Metadata } from 'next'
import { ThemeProvider } from '@/components/ui/theme-provider'
import localFont from 'next/font/local'
import { Footer, Header } from '@/components/layout'
import { NextIntlClientProvider } from 'next-intl'
import { getMessages } from 'next-intl/server'

const myFont = localFont({
	src: [
		{
			path: '../../public/fonts/Tektur-Regular.ttf',
			weight: '400',
			style: 'normal'
		},
		{
			path: '../../public/fonts/Tektur-Bold.ttf',
			weight: '700',
			style: 'normal'
		}
	]
})

export const metadata: Metadata = {
	title: 'Create Next App',
	description: 'Generated by create next app'
}

export default async function RootLayout({
	children,
	params: { locale }
}: Readonly<{
	children: React.ReactNode
	params: { locale: string }
}>) {
	const messages = await getMessages()

	// console.log('locale: ', locale)

	return (
		<html className='scroll-smooth scroll-pt-24' lang={locale}>
			<NextIntlClientProvider messages={messages}>
				<ThemeProvider>
					<body
						className={cn(
							'min-h-screen bg-background font-sans antialiased',
							myFont.className
						)}
					>
						<Header locale={locale} />
						<main className='min-h-screen w-full'>{children}</main>
						<Footer />
					</body>
				</ThemeProvider>
			</NextIntlClientProvider>
		</html>
	)
}
